# Generated by Django 6.0.3 on 2026-03-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_alter_category_options_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'businesses'},
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='directory.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fingerprint', 'business'), name='unique_support')],
            },
        ),
    ]
