# Generated by Django 6.0.3 on 2026-03-22 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_business_options_alter_business_logo_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
