# Generated by Django 6.0.3 on 2026-03-30 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featured',
            options={'verbose_name_plural': 'featured'},
        ),
        migrations.AlterField(
            model_name='featured',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='directory.business', unique=True),
        ),
    ]
