# Generated by Django 6.0.3 on 2026-03-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_alter_featured_options_alter_featured_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='directory.business'),
        ),
    ]
