# Generated by Django 6.0.3 on 2026-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_alter_featured_business'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_business_name'),
        ),
    ]
