# Generated by Django 6.0.3 on 2026-05-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_business_unique_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_business_email'),
        ),
    ]
